import type { RouteDoc } from './types';

/** Gateway 对外路由清单 — 与 proxy.ts / index.ts 保持同步 */
export const GATEWAY_ROUTE_CATALOG: RouteDoc[] = [
  // ── Gateway 自身 ──
  { path: '/health', method: 'get', tag: 'Gateway', summary: '网关健康检查', auth: 'none', upstream: 'gateway' },
  { path: '/', method: 'get', tag: 'Gateway', summary: '网关版本信息', auth: 'none', upstream: 'gateway' },

  // ── 账户 / mxmauth ──
  { path: '/api/v1/account/captcha/config', method: 'get', tag: 'Account', summary: '验证码是否启用', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/captcha', method: 'get', tag: 'Account', summary: '获取滑动拼图验证码', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/captcha/verify', method: 'post', tag: 'Account', summary: '校验滑动拼图', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/register', method: 'post', tag: 'Account', summary: '邮箱注册（需验证邮件）', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/login', method: 'post', tag: 'Account', summary: '用户登录', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/auth/providers', method: 'get', tag: 'Account', summary: '可用登录方式（OAuth/SMTP）', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/auth/mfa/verify', method: 'post', tag: 'Account', summary: '登录 MFA 验证', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/mfa/status', method: 'get', tag: 'Account', summary: 'MFA 状态', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/mfa/totp/setup', method: 'post', tag: 'Account', summary: 'TOTP 绑定准备', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/mfa/totp/enable', method: 'post', tag: 'Account', summary: '启用 TOTP', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/mfa/totp/disable', method: 'post', tag: 'Account', summary: '关闭 TOTP', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/verify-email', method: 'get', tag: 'Account', summary: '验证邮箱', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/resend-verification', method: 'post', tag: 'Account', summary: '重发验证邮件', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/forgot-password', method: 'post', tag: 'Account', summary: '忘记密码', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/reset-password', method: 'post', tag: 'Account', summary: '重置密码', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/oauth/google/start', method: 'get', tag: 'Account', summary: 'Google OAuth 开始', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/oauth/google/callback', method: 'get', tag: 'Account', summary: 'Google OAuth 回调', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/oauth/github/start', method: 'get', tag: 'Account', summary: 'GitHub OAuth 开始', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/oauth/github/callback', method: 'get', tag: 'Account', summary: 'GitHub OAuth 回调', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/logout', method: 'post', tag: 'Account', summary: '用户登出', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/refresh-token', method: 'post', tag: 'Account', summary: '刷新 Access Token', auth: 'none', upstream: 'mxmauth' },
  { path: '/api/v1/account/profile', method: 'get', tag: 'Account', summary: '获取个人资料', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/profile', method: 'put', tag: 'Account', summary: '更新个人资料', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/password', method: 'put', tag: 'Account', summary: '修改密码', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/settings', method: 'get', tag: 'Account', summary: '获取用户设置', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/settings', method: 'put', tag: 'Account', summary: '更新用户设置', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/membership', method: 'get', tag: 'Account', summary: '获取会员信息', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/media', method: 'get', tag: 'Account', summary: '获取用户媒体资源列表', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/agents', method: 'get', tag: 'Account', summary: '获取用户助手列表', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/updateAgents', method: 'put', tag: 'Account', summary: '更新用户助手关联', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/updateMedia', method: 'put', tag: 'Account', summary: '更新用户媒体关联', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/api-keys', method: 'get', tag: 'API Keys', summary: '列出个人 API Key', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/api-keys', method: 'post', tag: 'API Keys', summary: '创建个人 API Key', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/api-keys/{id}', method: 'delete', tag: 'API Keys', summary: '删除个人 API Key', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/account/admin/users', method: 'get', tag: 'Account Admin', summary: '管理员：用户列表', auth: 'admin', upstream: 'mxmauth' },
  { path: '/api/v1/account/admin/user_profile', method: 'put', tag: 'Account Admin', summary: '管理员：更新用户资料', auth: 'admin', upstream: 'mxmauth' },
  { path: '/api/v1/account/admin/users/{id}/status', method: 'put', tag: 'Account Admin', summary: '管理员：更新用户状态', auth: 'admin', upstream: 'mxmauth' },
  { path: '/api/v1/account/admin/users/{id}/force-logout', method: 'post', tag: 'Account Admin', summary: '管理员：强制登出用户', auth: 'admin', upstream: 'mxmauth' },
  { path: '/api/v1/account/health', method: 'get', tag: 'Account', summary: 'mxmauth 健康检查', auth: 'none', upstream: 'mxmauth' },

  // ── 资源 / mxmauth ──
  { path: '/api/v1/assets/folders', method: 'get', tag: 'Assets', summary: '列出资源文件夹', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/assets/folders', method: 'post', tag: 'Assets', summary: '创建资源文件夹', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/assets/folders/{id}', method: 'put', tag: 'Assets', summary: '更新资源文件夹', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/assets/folders/{id}', method: 'delete', tag: 'Assets', summary: '删除资源文件夹', auth: 'jwt', upstream: 'mxmauth' },

  // ── Partner / mxmauth ──
  { path: '/api/v1/partner/apps', method: 'get', tag: 'Partner', summary: '列出 Partner 应用', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/partner/apps', method: 'post', tag: 'Partner', summary: '创建 Partner 应用', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/partner/apps/{id}/settings', method: 'put', tag: 'Partner', summary: '更新 Partner 应用设置', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/partner/apps/{id}/slugs', method: 'put', tag: 'Partner', summary: '配置 Partner 可用 slug', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/partner/apps/{id}/rotate-secret', method: 'post', tag: 'Partner', summary: '轮换 Partner 密钥', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/partner/apps/{id}/stats', method: 'get', tag: 'Partner', summary: 'Partner 调用统计', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/partner/me/uploads', method: 'post', tag: 'Partner', summary: 'Partner 终端用户上传', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/partner/auth/sms/send', method: 'post', tag: 'Partner', summary: 'Partner 短信验证码发送', auth: 'jwt', upstream: 'mxmauth' },
  { path: '/api/v1/partner/auth/sms/verify', method: 'post', tag: 'Partner', summary: 'Partner 短信验证码校验', auth: 'jwt', upstream: 'mxmauth' },

  // ── 支付 / mxmpay ──
  { path: '/api/v1/payment/create', method: 'post', tag: 'Payment', summary: '创建支付订单', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/payment', method: 'get', tag: 'Payment', summary: '查询订单列表', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/payment/{orderId}', method: 'get', tag: 'Payment', summary: '获取订单详情', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/payment/confirm', method: 'post', tag: 'Payment', summary: '确认支付', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/payment/{orderId}/cancel', method: 'post', tag: 'Payment', summary: '取消订单', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/payment/stats/overview', method: 'get', tag: 'Payment', summary: '支付统计概览', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/payment/admin/orders', method: 'get', tag: 'Payment Admin', summary: '管理员：订单列表', auth: 'admin', upstream: 'mxmpay' },
  { path: '/api/v1/payment/admin/voucher/issue', method: 'post', tag: 'Payment Admin', summary: '管理员：发放代金券', auth: 'admin', upstream: 'mxmpay' },
  { path: '/api/v1/payment/webhook/{channel}', method: 'post', tag: 'Payment', summary: '支付渠道 Webhook 回调', auth: 'webhook', upstream: 'mxmpay' },

  // ── 钱包 / mxmpay ──
  { path: '/api/v1/wallets/assets', method: 'get', tag: 'Wallet', summary: '系统支持的资产列表', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/wallets', method: 'get', tag: 'Wallet', summary: '用户全部资产余额', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/wallets/{assetCode}', method: 'get', tag: 'Wallet', summary: '单个资产余额', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/wallets/{assetCode}/transactions', method: 'get', tag: 'Wallet', summary: '资产交易流水', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/wallets/{assetCode}/deposit', method: 'post', tag: 'Wallet', summary: '充值 / 增加余额', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/wallets/{assetCode}/withdraw', method: 'post', tag: 'Wallet', summary: '扣减余额', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/wallets/payment', method: 'post', tag: 'Wallet', summary: '钱包支付（消费扣款）', auth: 'jwt', upstream: 'mxmpay' },
  { path: '/api/v1/wallets/tasks', method: 'get', tag: 'Wallet', summary: '钱包任务列表', auth: 'jwt', upstream: 'mxmpay' },

  // ── Task V2 / mxmcgi ──
  { path: '/api/v2/tasks/form-config', method: 'get', tag: 'Task V2', summary: '获取业务表单配置', description: 'query: scope, taskKey, subtype', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/tasks/form-config/list', method: 'get', tag: 'Task V2', summary: '列出 scope 下可用业务', description: 'query: scope', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/tasks/run', method: 'post', tag: 'Task V2', summary: '运行业务任务（推荐入口）', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/tasks', method: 'get', tag: 'Task V2', summary: '当前用户任务列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/tasks/admin', method: 'get', tag: 'Task V2 Admin', summary: '管理员任务列表', auth: 'admin', upstream: 'mxmcgi' },
  { path: '/api/v2/tasks/by-user/{userId}', method: 'get', tag: 'Task V2 Admin', summary: '按用户查询任务', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/tasks/{taskId}', method: 'get', tag: 'Task V2', summary: '获取任务详情', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/tasks/{taskId}', method: 'delete', tag: 'Task V2', summary: '删除任务', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/tasks/{taskId}/cancel', method: 'post', tag: 'Task V2', summary: '取消任务', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/tasks/{taskId}/recover', method: 'post', tag: 'Task V2', summary: '恢复任务', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/tasks/{taskId}/retry', method: 'post', tag: 'Task V2', summary: '重试任务', auth: 'jwt', upstream: 'mxmcgi' },

  // ── 开放 API / mxmcgi ──
  { path: '/api/v1/open/jobs', method: 'get', tag: 'Open API', summary: 'Partner session 任务列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/open/{slug}', method: 'get', tag: 'Open API', summary: '获取已发布 API Manifest', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/open/{slug}/run', method: 'post', tag: 'Open API', summary: '调用已发布 API', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/open/{slug}/jobs/{jobId}', method: 'get', tag: 'Open API', summary: '查询开放 API 任务状态', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/open/{slug}/jobs/{jobId}/events', method: 'get', tag: 'Open API', summary: 'SSE 订阅任务事件', auth: 'jwt', upstream: 'mxmcgi' },

  // ── 发布管理 / mxmcgi ──
  { path: '/api/v1/account/published-apis', method: 'get', tag: 'Published API', summary: '我的已发布 API 列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/account/published-apis', method: 'post', tag: 'Published API', summary: '发布 API', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/account/published-apis/{id}', method: 'put', tag: 'Published API', summary: '更新已发布 API', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/account/published-apis/{id}/republish', method: 'post', tag: 'Published API', summary: '重新发布 API', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/account/published-apis/stats', method: 'get', tag: 'Published API', summary: '发布 API 统计汇总', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/account/published-apis/{id}/stats', method: 'get', tag: 'Published API', summary: '单个 API 统计', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/account/usage/summary', method: 'get', tag: 'Account', summary: '全平台用量统计汇总', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/account/usage/events', method: 'get', tag: 'Account', summary: '全平台用量调用明细分页', auth: 'jwt', upstream: 'mxmcgi' },

  // ── Agent / mxmcgi ──
  { path: '/api/v1/agent/catalog', method: 'get', tag: 'Agent', summary: 'Agent 业务目录', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/agent/conversations', method: 'get', tag: 'Agent V2', summary: '会话列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/agent/conversations', method: 'post', tag: 'Agent V2', summary: '创建会话', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/agent/conversations/{id}/messages', method: 'post', tag: 'Agent V2', summary: '发送消息并入队 run', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/agent/conversations/{id}/stream', method: 'get', tag: 'Agent V2', summary: 'SSE 事件流（cursor 回放）', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v2/agent/runs/{id}/cancel', method: 'post', tag: 'Agent V2', summary: '取消 run', auth: 'jwt', upstream: 'mxmcgi' },

  // ── Smartflow / mxmcgi ──
  { path: '/api/v1/smartflows', method: 'get', tag: 'Smartflow', summary: '工作流列表', auth: 'none', upstream: 'mxmcgi' },
  { path: '/api/v1/smartflows/{id}', method: 'get', tag: 'Smartflow', summary: '工作流详情', auth: 'none', upstream: 'mxmcgi' },
  { path: '/api/v1/smartflows', method: 'post', tag: 'Smartflow', summary: '创建工作流', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/smartflows/{id}', method: 'put', tag: 'Smartflow', summary: '更新工作流', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/smartflows/{id}', method: 'delete', tag: 'Smartflow', summary: '删除工作流', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/smartflows/{id}/execute', method: 'post', tag: 'Smartflow', summary: '执行工作流', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/smartflow-tasks', method: 'get', tag: 'Smartflow', summary: 'Smartflow 执行任务列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/smartflow-tasks/{id}', method: 'get', tag: 'Smartflow', summary: 'Smartflow 执行任务详情', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/smartflow-tasks/{id}/pause', method: 'post', tag: 'Smartflow', summary: '暂停 Smartflow 任务', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/smartflow-tasks/{id}/cancel', method: 'post', tag: 'Smartflow', summary: '取消 Smartflow 任务', auth: 'jwt', upstream: 'mxmcgi' },

  // ── 助手 / mxmcgi ──
  { path: '/api/v1/agents', method: 'get', tag: 'Agents', summary: '助手列表', auth: 'none', upstream: 'mxmcgi' },
  { path: '/api/v1/agents/{agentId}', method: 'get', tag: 'Agents', summary: '助手详情', auth: 'none', upstream: 'mxmcgi' },

  // ── 媒体 / 存储 / mxmcgi ──
  { path: '/api/v1/media/graph/{taskId}', method: 'get', tag: 'Media', summary: '获取图像任务媒体', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/media/video/{taskId}', method: 'get', tag: 'Media', summary: '获取视频任务媒体', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/media/writing/{taskId}', method: 'get', tag: 'Media', summary: '获取写作任务内容', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/media/writing/{taskId}/office-embed-url', method: 'get', tag: 'Media', summary: '签发写作 PPTX Office 公网嵌入 URL', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/media/audio/{taskId}', method: 'get', tag: 'Media', summary: '获取音频任务媒体', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/media/public/object/{objectId}', method: 'get', tag: 'Media', summary: '公开读用户上传对象', auth: 'none', upstream: 'mxmcgi' },
  { path: '/api/v1/media/public/writing/{taskId}', method: 'get', tag: 'Media', summary: '公网签名读写作 PPTX（Office Online）', auth: 'none', upstream: 'mxmcgi' },
  { path: '/api/v1/cgi/upload/temp', method: 'post', tag: 'Upload', summary: '临时文件上传', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/cgi/upload/assets', method: 'post', tag: 'Upload', summary: '资源文件上传', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/storage', method: 'get', tag: 'Storage', summary: '用户存储概览', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/static/{path}', method: 'get', tag: 'Storage', summary: '系统静态资源（公开）', auth: 'none', upstream: 'mxmcgi' },

  // ── 写作 / 音频 / 视频（遗留 CGI，推荐 Task V2）──
  { path: '/api/v1/writing/models', method: 'get', tag: 'Writing (Legacy)', summary: '写作模型列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/writing/completion/{modelName}', method: 'post', tag: 'Writing (Legacy)', summary: '写作补全（支持 SSE）', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/audio/models', method: 'get', tag: 'Audio (Legacy)', summary: '音频模型列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/audio/voices', method: 'get', tag: 'Audio (Legacy)', summary: 'MiniMax 音色列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/audio/voice-clone', method: 'post', tag: 'Audio (Legacy)', summary: 'MiniMax 音色克隆', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/audio/{modelName}', method: 'post', tag: 'Audio (Legacy)', summary: '音频生成', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/cgi/video/models', method: 'get', tag: 'Video (Legacy)', summary: '视频模型列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/cgi/video/generate', method: 'post', tag: 'Video (Legacy)', summary: '视频生成', auth: 'jwt', upstream: 'mxmcgi' },
  {
    path: '/api/v1/cgi/graph/{modelName}',
    method: 'post',
    tag: 'Graph (Legacy)',
    summary: '图像生成（已废弃）',
    description: 'mxmcgi 对旧 /graph 返回 410，请改用 POST /api/v2/tasks/run',
    auth: 'jwt',
    upstream: 'mxmcgi',
    deprecated: true,
  },

  // ── 知识库 / 角色 / 搜索 / mxmcgi ──
  { path: '/api/v1/knowledge/bases', method: 'get', tag: 'Knowledge', summary: '知识库列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/knowledge/bases', method: 'post', tag: 'Knowledge', summary: '创建知识库', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/knowledge/bases/{id}/documents', method: 'post', tag: 'Knowledge', summary: '上传知识库文档', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/knowledge/bases/{id}/search', method: 'post', tag: 'Knowledge', summary: '知识库检索', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/search/web', method: 'post', tag: 'Search', summary: 'Web 搜索', auth: 'jwt', upstream: 'mxmcgi' },

  // ── 系统 / Admin / mxmcgi ──
  { path: '/api/v1/system/models', method: 'get', tag: 'System', summary: '系统模型列表', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/system/bills', method: 'get', tag: 'System', summary: '用户账单', auth: 'jwt', upstream: 'mxmcgi' },
  { path: '/api/v1/system/admin/stats', method: 'get', tag: 'System Admin', summary: '管理员统计', auth: 'admin', upstream: 'mxmcgi' },
  { path: '/api/v1/system/admin/providers/models', method: 'get', tag: 'System Admin', summary: 'Provider 模型管理', auth: 'admin', upstream: 'mxmcgi' },
  { path: '/api/v1/system/admin/quality-eval/rubrics', method: 'get', tag: 'System Admin', summary: '写作质检评分配置', auth: 'admin', upstream: 'mxmcgi' },
  { path: '/api/v1/system/admin/quality-eval/runs', method: 'post', tag: 'System Admin', summary: '发起写作质检评估', auth: 'admin', upstream: 'mxmcgi' },
  { path: '/api/v1/admin/storage', method: 'get', tag: 'System Admin', summary: 'Admin 系统存储', auth: 'admin', upstream: 'mxmcgi' },

  // ── 通知 / mxmnotify ──
  { path: '/api/v1/notifications', method: 'get', tag: 'Notifications', summary: '通知列表', auth: 'jwt', upstream: 'mxmnotify' },
  { path: '/api/v1/notifications/{notificationId}/read', method: 'put', tag: 'Notifications', summary: '标记通知已读', auth: 'jwt', upstream: 'mxmnotify' },
  { path: '/api/v1/notifications/read-all', method: 'put', tag: 'Notifications', summary: '全部标记已读', auth: 'jwt', upstream: 'mxmnotify' },
  { path: '/api/v1/notifications/{notificationId}', method: 'delete', tag: 'Notifications', summary: '删除通知', auth: 'jwt', upstream: 'mxmnotify' },
  { path: '/api/v1/sse/{userId}', method: 'get', tag: 'Notifications', summary: 'SSE 实时通知流', auth: 'jwt', upstream: 'mxmnotify' },
  { path: '/api/v1/tasks/{taskId}', method: 'get', tag: 'Notifications', summary: '通知侧任务查询', auth: 'jwt', upstream: 'mxmnotify' },
  { path: '/api/v1/task-events/status-changed', method: 'post', tag: 'Notifications', summary: '任务状态变更事件（内部）', auth: 'jwt', upstream: 'mxmnotify' },

  // ── WebSocket（非 REST，仅文档说明）──
  {
    path: '/api/v1/ws/notifications',
    method: 'get',
    tag: 'WebSocket',
    summary: 'WebSocket 通知连接',
    description: '协议升级为 WebSocket，非 HTTP JSON 响应。详见 gateway WebSocket 代理配置。',
    auth: 'jwt',
    upstream: 'mxmnotify',
  },
  {
    path: '/api/v1/ws/open/{slug}/jobs/{jobId}',
    method: 'get',
    tag: 'WebSocket',
    summary: '开放 API WebSocket 任务订阅',
    description: '协议升级为 WebSocket。',
    auth: 'jwt',
    upstream: 'mxmcgi',
  },
];

export const OPENAPI_TAGS: Array<{ name: string; description: string }> = [
  { name: 'Gateway', description: '网关自身健康检查与元信息' },
  { name: 'Account', description: '用户注册、登录、资料与设置（mxmauth）' },
  { name: 'Account Admin', description: '账户管理员接口' },
  { name: 'API Keys', description: '个人访问凭证管理' },
  { name: 'Assets', description: '用户资源文件夹' },
  { name: 'Partner', description: 'Partner 集成与终端用户' },
  { name: 'Payment', description: '支付订单与 Webhook（mxmpay）' },
  { name: 'Payment Admin', description: '支付管理员接口' },
  { name: 'Wallet', description: '多资产钱包（mxmpay）' },
  { name: 'Task V2', description: '统一业务任务入口（mxmcgi，推荐使用）' },
  { name: 'Task V2 Admin', description: '任务管理员接口' },
  { name: 'Open API', description: '已发布开放 API 调用' },
  { name: 'Published API', description: '开放 API 发布与管理' },
  { name: 'Agent', description: 'Agent 业务目录' },
  { name: 'Smartflow', description: 'Smartflow 工作流' },
  { name: 'Agents', description: '助手列表与 Agent Chat' },
  { name: 'Media', description: '任务媒体访问' },
  { name: 'Upload', description: '文件上传' },
  { name: 'Storage', description: '用户与系统存储' },
  { name: 'Writing (Legacy)', description: '遗留写作接口，推荐 Task V2' },
  { name: 'Audio (Legacy)', description: '遗留音频接口，推荐 Task V2' },
  { name: 'Video (Legacy)', description: '遗留视频接口，推荐 Task V2' },
  { name: 'Graph (Legacy)', description: '已废弃，请用 Task V2' },
  { name: 'Knowledge', description: '知识库' },
  { name: 'Search', description: '搜索引擎' },
  { name: 'System', description: '系统信息与账单' },
  { name: 'System Admin', description: '系统管理员接口' },
  { name: 'Notifications', description: '通知、SSE、任务事件（mxmnotify）' },
  { name: 'WebSocket', description: 'WebSocket 长连接（非 REST）' },
];
